import { AbstractComponent } from './abstract/abstract.component';
import { PublicationComponent } from './publication/publication.component';
import { FragmentComponent } from './fragment/fragment.component';
import { ContentComponent } from './content/content.component';
import { SrcContentComponent } from './content-src/content-src.component';
import { TxtContentComponent } from './content-txt/content-txt.component';
export { AbstractComponent };
export { PublicationComponent };
export { FragmentComponent };
export { ContentComponent };
export { SrcContentComponent };
export { TxtContentComponent };
export declare const AllComponents: (typeof AbstractComponent | typeof PublicationComponent | typeof FragmentComponent | typeof SrcContentComponent | typeof TxtContentComponent)[];
