export { KioBackendService } from './api/services/backend.service'
export { KioLocaleService } from './i18n/service/locale.service'
export { KioNg2StructureModule } from './module'
export { SomeClass } from './classes/some.class'
/*export { AbstractComponent } from './components/abstract/abstract.component'
export { PublicationComponent } from './components/publication/publication.component'
export { FragmentComponent } from './components/fragment/fragment.component'
export { ContentComponent } from './components/content/content.component'
export { SrcContentComponent } from './components/content-src/content-src.component'
export { TxtContentComponent } from './components/content-txt/content-txt.component'
*/
export * from './interfaces'